server:
  port: 7070
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  r2dbc:
    generate-ddl: true
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: