server:
  port: 1010

stripe:
  secretKey: your_stripe_secret_key_here

spring:
  application:
    name: payment-service
  datasource:
    url: r2dbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    nonSecurePort: 8080
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
